### ISSUE TITLE
"simulation output stats.R" not in repo

### ISSUE THREAD

**Issue by gavinfay** [acarrharris/Fluke-MSE-simulation#3]
The wrapper scripts contain reference to a output statistics script 
`simulation output stats.R` following the predictions of catches under the new alternative regulations.
@acarrharris can you please add this to the repo?

**Comment by acarrharris** [comment]
Added "simulation stats output.R" to repo. This file combines catch metrics from the simulation and compares them to MRIP estimates. Right now it makes several .txt files which then get read into an excel file. I still need to add the excel file and pipe the .txt files to it. Maybe there's a better way to do this.

The file also includes code for comparing in-sample model predictions to MRIP estimates. For example, if we calibrated to 2019 and predicted fishing year 2018, 2017, or 2016--contingent on stock conditions and regulations in those years-- we could compare model predictions of catch and and directed trips with estimates from MRIP. This part of the code is commented out for now.
