### ISSUE TITLE
modify variance of negative binomial when drawing catch per trip values

### ISSUE THREAD

**Issue by gavinfay** [acarrharris/Fluke-MSE-simulation#6]
Currently only the mean of the catch per trip is adjusted based on relative stock availability when computing catch draws for the predictions.

Adjust `size` parameter of the negative binomial assuming same CV as calibration year.

**Comment by acarrharris** [comment]
I added code in "predicted_catch_per_trip.R" that, for each region, computes a size parameter in the prediction year (sf_size_new) such that CV is constant between calibration and prediction year. Mean parameters in the prediction year (sf_mu_new) are scaled relative to expected total catch using the expansion factor from each region.
